### ISSUE TITLE
PRESETS PRESETS PRESETS (i2)

### ISSUE THREAD

**Issue by sonnyvesali** [Nokhte/nokhte#360]
### Todo
- [x] session_phone_guide widget
- [x] new exit protocol
- [x] take out gyroscope (for consistency) => make new exit screen / protocol
- [x] make the algorithm flexible phone allocation depending on the session
- [x] make the presets screen
- [x] adjust the database to include the preset information
- [x] the new qr code flow (screen splitting will be necessary here)
- [x] Show the rotation between the `Scan to Join / ${session_type}`
- [ ] transfer app store ownerships
- [x] figure out monetization integration (where is it going to be now?)

**Comment by sonnyvesali** [comment]
we are going to need to refactor (product wise) preset instructions, the rough mechanics of it are going to be the same a lot of the widget code is done, it's now more about composing them & messaging, so not as bad as we think

**Comment by sonnyvesali** [comment]
fix the session qr code query thing to make it stream basaed

**Comment by sonnyvesali** [comment]
go through any part of the app where there is timed moving of the padding of smart text & check to make sure it's good

**Comment by sonnyvesali** [comment]
do we want collaborator is offline for the async instructions????
