### ISSUE TITLE
revise presets & session instructions

### ISSUE THREAD

**Issue by sonnyvesali** [Nokhte/nokhte#420]
## Todo
- [ ] remove socratic visibility (temporarily for this current cycle)
- [ ] refactor expanded preset cards into its own article type component
- [ ] refactor consultation to use solo hybrid with holding instead of tapping
